config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  # Home page route
  root "index_home#index"
  
  # Devise routes for user authentication
  devise_for :users

  # Cart routes
  resource :cart, only: [:show] do
    # POST method to add an item to the cart
    post 'add_item/:item_id', to: 'carts#add_item', as: 'add_item'
    delete 'remove_item', to: 'carts#remove_item', as: 'remove_item'
  end

  #Checkout routes
  get 'checkout', to: 'checkout#show'
  post 'process_payment', to: 'checkout#process_payment'
  get 'confirmation', to: 'checkout#confirmation'
  # resource :checkout, controller: 'checkout', only: [:show, :create] do
  #   post 'process_payment', on: :collection
  #   get 'confirmation', on: :collection
  # end

  # CartItems routes to handle item-specific actions in the cart
  resources :cart_items, only: [:create, :destroy, :increase] do
    member do
      patch :increase
      patch :decrease
    end
  end

  # Admin namespace routes
  namespace :admin do
    resources :items
    get 'dashboard', to: 'home#index'
    resources :user_list
    resources :transactions
  end

  # User routes for profile management
  resource :user, only: [:show, :edit, :update]

  # Static pages routes
  get 'about_us', to: 'pages#about_us'

  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check

  # Custom routes for admin management
  get 'admin/pending/index'
  get 'admin/home/index'

  # IndexHome routes
  get 'index_home/index'
  # resources :items, only: [:index]
  get 'search_items', to: 'items#search', as: 'search_items'
  resources :items, only: [:show] do
    member do
      get 'description', to: 'items#description', as: 'description'
    end
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    "admin_"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  
  def total_price
    cart_items.joins(:item).sum('cart_items.quantity * items.price')
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
  
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }

  def calculate_total_price
    self.total_price = quantity * item.price
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :carts, through: :cart_items

  has_one_attached :image
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    has_many :transaction_items, dependent: :destroy
end

app/models/transaction_item.rb
class TransactionItem < ApplicationRecord
    belongs_to :transaction_record, class_name: 'Transaction'
end
  
  

app/models/user.rb
class User < ApplicationRecord
  has_one :cart
  has_many :cart_items, through: :cart
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    user_type == 'admin'
  end
end

app/controllers/admin/user_list_controller.rb
class Admin::UserListController < ApplicationController
    before_action :set_user, only: [:edit, :update, :destroy]
    before_action :authenticate_admin!
  
    # GET /admin/user_list
    def index
      @users = User.where(user_type: "buyer")
    end
  
    # GET /admin/user_list/new
    def new
      @user = User.new
    end
  
    # POST /admin/user_list
    def create
      @user = User.new(user_params.merge(user_type: "buyer")) # Ensure the user_type is set to "buyer"
      
      if @user.save
        redirect_to admin_user_list_index_path, notice: 'User was successfully created.'
      else
        render :new
      end
    end
  
    # GET /admin/user_list/:id/edit
    def edit
    end
  
    # PATCH/PUT /admin/user_list/:id
    def update
      if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end
      
      if @user.update(user_params)
        redirect_to admin_user_list_index_path, notice: 'User was successfully updated.'
      else
        render :edit
      end
    end
  
    # DELETE /admin/user_list/:id
    def destroy
      @user.destroy
      redirect_to admin_user_list_index_path, notice: 'User was successfully deleted.'
    end
  
    private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
  
    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :account_status, :contact_number, :address, :balance) # Add other permitted params as needed
    end
  end
  

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart = current_user.cart || current_user.create_cart

  end

  def add_item
    @cart = current_user.cart || current_user.create_cart
    item = Item.find(params[:item_id])

    # Check if the item already exists in the cart, increase the quantity if so
    @cart_item = @cart.cart_items.find_by(item_id: item.id)
    if @cart_item
      @cart_item.update(quantity: @cart_item.quantity + 1)
      @cart_item.update(total_price: @cart_item.item.price * @cart_item.quantity)
    else
      @cart.cart_items.create(item: item, quantity: 1)
    end
    flash[:alert] = "#{item.item_name} has been added to your cart."
    redirect_to root_path
  end

  def remove_item
    cart_item = CartItem.find(params[:cart_item_id])
    cart_item.destroy

    redirect_to cart_path
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :check_admin, only: [:edit, :update]

  def admin_only
    redirect_to root_path, alert: 'Access denied' unless current_user&.admin?
  end

  # GET /items or /items.json
  def index
    flash[:notice] = ' '
    @items = Item.all
  end

  def search
    @items = Item.where('item_name LIKE ?', "%#{params[:query]}%")
  end

  # GET /items/1 or /items/1.json
  def show
    @item = Item.find(params[:id])
  end

  


  def description
    @item = Item.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:item_name, :item_description, :price)
    end

    def check_admin
      unless current_user.admin?
        redirect_to items_path, alert: "You are not authorized to edit items."
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end
end

app/helpers/admin/user_list_helper.rb
module Admin::UserListHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/index_home_helper.rb
module IndexHomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/user_list/_form.html.erb
<%= form_with(model: @user, url: @user.new_record? ? admin_user_list_index_path : admin_user_list_path(@user), local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= notice %>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, required: true %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>

  <div class="field">
    <%= form.label :contact_number %>
    <%= form.text_field :contact_number %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :balance %>
    <%= form.number_field :balance, step: 0.01 %>
  </div>

  <%# Only show password fields for new user or when editing a user %>
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, required: @user.new_record? %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, required: @user.new_record? %>
  </div>

  <div class="submit-container">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/user_list/edit.html.erb
<div class="admin-container">
    
    <div class="admin-sidebar bg-gray-800">
        <p>
            <%= link_to admin_dashboard_path do %>
                <i class="fa-solid fa-table-columns"></i> Dashboard
            <% end %>
        </p>

        <p><%= link_to admin_transactions_path do %>
            <i class="fa-solid fa-box"></i> Transactions
        <% end %></p>

        <p><%= link_to admin_items_path do %>
            <i class="fa-solid fa-list"></i> Item List
        <% end %></p>

        <p class="current-page"><%= link_to admin_user_list_index_path do %>
            <i class="fa-solid fa-users"></i> Users
        <% end %></p>

        <p><%= render 'shared/logout_button' %></p>

    </div>
    <div class="admin-sidebar-content">
        <div class="content-header">
            <h1 class="content-title2">User List
                <span class="notice" ><%= notice %></span>
                <span class="item-buttons2"><br><%= link_to 'Back to User List', admin_user_list_index_path %></span></h1>
        </div>
        <div class="users-container2">
            <h2 class="submit-container">Edit User</h2>
            <%= render 'form' %>
            <%= notice %>
           
        </div>
    </div>
</div>

app/views/admin/user_list/index.html.erb
<div class="admin-container">
    
    <div class="admin-sidebar bg-gray-800">
        <p>
            <%= link_to admin_dashboard_path do %>
                <i class="fa-solid fa-table-columns"></i> Dashboard
            <% end %>
        </p>

        <p><%= link_to admin_transactions_path	do %>
            <i class="fa-solid fa-box"></i> Transactions
        <% end %></p>

        <p><%= link_to admin_items_path do %>
            <i class="fa-solid fa-list"></i> Item List
        <% end %></p>

        <p class="current-page"><%= link_to admin_user_list_index_path do %>
            <i class="fa-solid fa-users"></i> Users
        <% end %></p>

        <p><%= render 'shared/logout_button' %></p>

    </div>
    <div class="admin-sidebar-content">
        <div class="content-header">
            <h1 class="content-title">
                User List
                <span class="notice" ><%= notice %></span>
                <span class="item-buttons">
                    <%= link_to '+ Create', new_admin_user_list_path %>
                </span>
            </h1>
        </div>
        <div class="users-container">
            <table cellspacing="0">
                <thead>
                    <th>User ID</th>
                    <th>Email</th>
                    <th>Name</th>
                    <th>Contact Number</th>
                    <th>Address</th>
                    <th>Balance</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    <% @users.each do |user| %>
                        <tr>
                            <td><%= user.id %></td>
                            <td><%= user.email %></td>
                            <td><%= user.name.present? ? user.name : "(Not Provided Yet)" %></td>
                            <td><%= user.contact_number.present? ? user.contact_number : "(Not Provided Yet)" %></td>
                            <td><%= user.address.present? ? user.address : "(Not Provided Yet)" %></td>
                            <td><%= user.balance %></td>
                            <td>
                                <%= link_to "Edit", edit_admin_user_list_path(user) %>
                                <%= button_to "Delete", admin_user_list_path(user), method: :delete %>
                            </td>
                        </tr>
                        <tr>
                            <td class="table-row-gap"></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/admin/user_list/new.html.erb
<div class="admin-container">
    
    <div class="admin-sidebar bg-gray-800">
        <p>
            <%= link_to admin_dashboard_path do %>
                <i class="fa-solid fa-table-columns"></i> Dashboard
            <% end %>
        </p>

        <p><%= link_to admin_transactions_path do %>
            <i class="fa-solid fa-box"></i> Transactions
        <% end %></p>

        <p><%= link_to admin_items_path do %>
            <i class="fa-solid fa-list"></i> Item List
        <% end %></p>

        <p class="current-page"><%= link_to admin_user_list_index_path do %>
            <i class="fa-solid fa-users"></i> Users
        <% end %></p>

        <p><%= render 'shared/logout_button' %></p>

    </div>
    <div class="admin-sidebar-content">
        <div class="content-header">
            <h1 class="content-title2">User List
                <span class="notice" ><%= notice %></span>
                <span class="item-buttons2"><br><%= link_to 'Back to User List', admin_user_list_index_path %></span></h1>
        </div>
        <div class="users-container2">
            <h2 class="submit-container">Create User</h2>
           <%= render 'form' %>
        </div>
    </div>
</div>