config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  # Home page route
  root "index_home#index"
  
  # Devise routes for user authentication
  devise_for :users

  # Cart routes
  resource :cart, only: [:show] do
    # POST method to add an item to the cart
    post 'add_item/:item_id', to: 'carts#add_item', as: 'add_item'
    delete 'remove_item', to: 'carts#remove_item', as: 'remove_item'
  end

  #Checkout routes
  get 'checkout', to: 'checkout#show'
  post 'process_payment', to: 'checkout#process_payment'
  get 'confirmation', to: 'checkout#confirmation'
  # resource :checkout, controller: 'checkout', only: [:show, :create] do
  #   post 'process_payment', on: :collection
  #   get 'confirmation', on: :collection
  # end

  # CartItems routes to handle item-specific actions in the cart
  resources :cart_items, only: [:create, :destroy, :increase] do
    member do
      patch :increase
      patch :decrease
    end
  end

  # Admin namespace routes
  namespace :admin do
    resources :items
    get 'dashboard', to: 'home#index'
    resources :user_list
    resources :transactions
  end

  # User routes for profile management
  resource :user, only: [:show, :edit, :update]

  # Static pages routes
  get 'about_us', to: 'pages#about_us'

  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check

  # Custom routes for admin management
  get 'admin/pending/index'
  get 'admin/home/index'

  # IndexHome routes
  get 'index_home/index'
  # resources :items, only: [:index]
  get 'search_items', to: 'items#search', as: 'search_items'
  resources :items, only: [:show] do
    member do
      get 'description', to: 'items#description', as: 'description'
    end
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    "admin_"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  
  def total_price
    cart_items.joins(:item).sum('cart_items.quantity * items.price')
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
  
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }

  def calculate_total_price
    self.total_price = quantity * item.price
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :carts, through: :cart_items

  has_one_attached :image
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    has_many :transaction_items, dependent: :destroy
end

app/models/transaction_item.rb
class TransactionItem < ApplicationRecord
    belongs_to :transaction_record, class_name: 'Transaction'
end
  
  

app/models/user.rb
class User < ApplicationRecord
  has_one :cart
  has_many :cart_items, through: :cart
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    user_type == 'admin'
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart = current_user.cart || current_user.create_cart

  end

  def add_item
    @cart = current_user.cart || current_user.create_cart
    item = Item.find(params[:item_id])

    # Check if the item already exists in the cart, increase the quantity if so
    @cart_item = @cart.cart_items.find_by(item_id: item.id)
    if @cart_item
      @cart_item.update(quantity: @cart_item.quantity + 1)
      @cart_item.update(total_price: @cart_item.item.price * @cart_item.quantity)
    else
      @cart.cart_items.create(item: item, quantity: 1)
    end
    flash[:alert] = "#{item.item_name} has been added to your cart."
    redirect_to root_path
  end

  def remove_item
    cart_item = CartItem.find(params[:cart_item_id])
    cart_item.destroy

    redirect_to cart_path
  end

end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action :authenticate_user!
  before_action :check_payment_status, only: [:confirmation]

  def show
    @cart = current_user.cart
    @total_amount = @cart.cart_items.sum { |item| item.quantity * item.item.price }
  end

  def process_payment
    @cart = current_user.cart
    @total_amount = @cart.cart_items.sum { |item| item.quantity * item.item.price }
  
    if current_user.balance >= @total_amount
      current_user.update(balance: current_user.balance - @total_amount)
      # Simulate payment logic (this is where you'd integrate Paymongo in the future)
      transaction = Transaction.create(cart_id: @cart.id, user_email: current_user.email, total_amount: @total_amount)
      transaction_items = @cart.cart_items.map do |item|
        { transaction_id: transaction.id, cart_id: item.cart_id, item_name: item.item.item_name, item_quantity: item.quantity }
      end
      TransactionItem.insert_all(transaction_items)
      # Paymongo Logic
      payment_successful = true # Simulate payment success, replace with real logic
    end

    if payment_successful
      session[:payment_successful] = true # Store the success flag in the session
      @cart.cart_items.destroy_all # Clear cart after payment
      redirect_to confirmation_path
    else
      redirect_to checkout_path, notice: "Payment failed. Please try again."
    end
  end
  
  
  
  def confirmation
    # This will only be called if the payment was successful
    session.delete(:payment_successful)
  end

  private

  def check_payment_status
    # Check if the payment was successful before accessing the confirmation page
    unless session[:payment_successful]
      redirect_to checkout_path, alert: "You need to complete the payment before proceeding."
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :check_admin, only: [:edit, :update]

  def admin_only
    redirect_to root_path, alert: 'Access denied' unless current_user&.admin?
  end

  # GET /items or /items.json
  def index
    flash[:notice] = ' '
    @items = Item.all
  end

  def search
    @items = Item.where('item_name LIKE ?', "%#{params[:query]}%")
  end

  # GET /items/1 or /items/1.json
  def show
    @item = Item.find(params[:id])
  end

  


  def description
    @item = Item.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:item_name, :item_description, :price)
    end

    def check_admin
      unless current_user.admin?
        redirect_to items_path, alert: "You are not authorized to edit items."
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path, notice: 'Profile updated successfully'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :contact_number, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/index_home_helper.rb
module IndexHomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transaction_items_helper.rb
module TransactionItemsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb

<% if @cart.cart_items.any? %>

<h2 class="mt-6 text-2xl text-violet-900 text-center font-bold	">Your Cart</h2>
<div class="w-3/5 mx-auto">
  <div class="overflow-x-auto"></div>
      <table class="w-full text-sm text-left text-gray-500 ">
          <thead class="text-xs text-white uppercase bg-violet-900">
              <tr>
                  <th scope="col" class="px-6 py-3">
                      Item Name
                  </th>
                  <th scope="col" class="px-6 py-3">
                      Quantity
                  </th>
                  <th scope="col" class="px-6 py-3">
                      Price
                  </th>
              </tr>
          </thead>
          <tbody>
            <% @cart.cart_items.each do |cart_item| %>
              <tr class="bg-white border-b">
                  <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    <%= cart_item.item.item_name %>
                  </th>
                  <td class="px-6 py-4 flex align-center">
                    <% if cart_item.quantity == 1 %>
                      <%= button_to 'Remove', remove_item_cart_path(cart_item_id: cart_item.id), method: :delete, class: 'bg-red-700 mr-3 px-2 text-white rounded' %>
                    <% end %>

                    <% if cart_item.quantity > 1 %>
                      <%= button_to " - ", decrease_cart_item_path(cart_item.item_id), class: "bg-red-700 mr-3 px-2 text-white rounded", method: :patch %> 
                    <% end %>
                    <%= cart_item.quantity %> <%= button_to " + ", increase_cart_item_path(cart_item.item_id), class: "bg-green-700 ml-3 px-2 text-white rounded", method: :patch %> 
                    
                  </td>
                  <td class="px-6 py-4">
                    <%= cart_item.quantity <= 1 ? number_to_currency(cart_item.item.price, unit: "₱", format: "%u%n") : number_to_currency(cart_item.total_price, unit: "₱", format: "%u%n") %>
                  </td>
              </tr>
            <% end %>
            <tr class="bg-violet-50 border-b">
                  <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    Total:
                  </th>
                  <td class="px-6 py-4">
                  </td>
                  <td class="bg-violet-100 px-6 py-4 text-green-700 font-medium">
                    <%= number_to_currency(@cart.total_price, unit: "₱", format: "%u%n") %>
                  </td>
              </tr>
          </tbody>
      </table>
      <div class="flex justify-end mt-6 mr-3">
        <%= link_to 'Proceed to Checkout', checkout_path, class: 'bg-violet-900 text-white px-6 py-3 rounded hover:bg-gray-500 mr-2' %>
      </div>
    </div>

  <% else %>
    <h2 class="mt-6 text-2xl text-violet-900 text-center font-bold	">Your Cart is empty.</h2>
  <% end %>

</div>
    


app/views/users/edit.html.erb

<%= form_for(@user, url: user_path, method: :put) do |f| %>

<div class="w-full">
     <h2 class="text-center text-violet-800 font-bold text-2xl uppercase mb-10 mt-10">Edit Profile</h2>
     <div class="bg-white p-10 rounded-lg shadow md:w-3/4 mx-auto lg:w-1/3">
       <form action="">
         <div class="mb-5">
          <%= f.label :email, class: "block mb-2 font-bold text-gray-600" %>
          <%= f.text_field :email, disabled: true, class: "border border-gray-300 shadow p-3 w-full rounded mb- bg-gray-300" %>
         </div>

         <div class="mb-5">
          <%= f.label :name, class: "block mb-2 font-bold text-gray-600" %>
          <%= f.text_field :name, class: "border border-gray-300 shadow p-3 w-full rounded mb-" %>
         </div>

         <div class="mb-5">
          <%= f.label :contact_number, class: "block mb-2 font-bold text-gray-600" %>
          <%= f.text_field :contact_number, class: "border border-gray-300 shadow p-3 w-full rounded mb-" %>
         </div>

         <div class="mb-5">
          <%= f.label :address, class: "block mb-2 font-bold text-gray-600" %>
          <%= f.text_field :address, class: "border border-gray-300 shadow p-3 w-full rounded mb-" %>
         </div>
          <%= notice %>
         <div class="flex flex-col items-center">
          <%= f.submit 'Update Profile', class: "block w-full !bg-violet-900 text-white font-bold !p-4 !rounded-lg hover:!bg-violet-950" %>
          <%= link_to 'Back', user_path, class: "block mt-4 w-1/2 bg-red-700 text-white font-bold p-3 rounded-lg text-center hover:!bg-red-800" %>
         </div>
         
       </form>
     </div>
   </div>
</div>

<% end %>

app/views/users/show.html.erb

<div class=" w-full">
  <div class="mt-24 max-w-xs rounded-2xl border bg-white p-10 text-center shadow-lg mx-auto">
      <img class="mx-auto mb-4 h-32 w-32 rounded-full shadow-lg" src="https://static.vecteezy.com/system/resources/thumbnails/009/292/244/small/default-avatar-icon-of-social-media-user-vector.jpg" alt="profile picture" />
      <h1 class="text-xl font-semibold text-slate-800"><%= @user.email %></h1>
      <h2 class="font-semibold text-slate-500"><%= @user.balance.present? ? number_to_currency(@user.balance, unit: "₱", format: "%u%n") : "Not provided" %></h2>
      <p class="mt-4 text-sm font-normal text-slate-800">
        <strong>Name:</strong>
        <%= @user.name.present? ? @user.name : "Not provided" %>
      </p>

      <p class="mt-4 text-sm font-normal text-slate-800">
        <strong>Contact Number:</strong>
        <%= @user.contact_number.present? ? @user.contact_number : "Not provided" %>
      </p>

      <p class="mt-4 text-sm font-normal text-slate-800">
        <strong>Address:</strong>
        <%= @user.address.present? ? @user.address : "Not provided" %>
      </p>
      <br>
      <div class="flex flex-col">
        <%= link_to 'Edit Profile', edit_user_path, class: "mt-8 rounded-3xl border-2 border-solid border-violet-900 px-8 py-2 font-semibold uppercase tracking-wide text-violet-900 hover:bg-violet-900 hover:text-white" %>
        <br>
        <%= link_to 'Transactions', transactions_path, class: "rounded-3xl border-2 border-solid border-violet-900 px-8 py-2 font-semibold uppercase tracking-wide text-violet-900 hover:bg-violet-900 hover:text-white" %>
        <br>
        <%= render 'shared/logout_button' %>
      </div>
      
  </div>
</div>
