config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  # Home page route
  root "index_home#index"
  
  # Devise routes for user authentication
  devise_for :users

  # Cart routes
  resource :cart, only: [:show] do
    # POST method to add an item to the cart
    post 'add_item/:item_id', to: 'carts#add_item', as: 'add_item'
    delete 'remove_item', to: 'carts#remove_item', as: 'remove_item'
  end

  #Checkout routes
  get 'checkout', to: 'checkout#show'
  post 'process_payment', to: 'checkout#process_payment'
  get 'confirmation', to: 'checkout#confirmation'
  # resource :checkout, controller: 'checkout', only: [:show, :create] do
  #   post 'process_payment', on: :collection
  #   get 'confirmation', on: :collection
  # end

  # CartItems routes to handle item-specific actions in the cart
  resources :cart_items, only: [:create, :destroy, :increase] do
    member do
      patch :increase
      patch :decrease
    end
  end

  # Admin namespace routes
  namespace :admin do
    resources :items
    get 'dashboard', to: 'home#index'
    resources :user_list
    resources :transactions
  end

  # User routes for profile management
  resource :user, only: [:show, :edit, :update]

  # Static pages routes
  get 'about_us', to: 'pages#about_us'

  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check

  # Custom routes for admin management
  get 'admin/pending/index'
  get 'admin/home/index'

  # IndexHome routes
  get 'index_home/index'
  # resources :items, only: [:index]
  get 'search_items', to: 'items#search', as: 'search_items'
  resources :items, only: [:show] do
    member do
      get 'description', to: 'items#description', as: 'description'
    end
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    "admin_"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  
  def total_price
    cart_items.joins(:item).sum('cart_items.quantity * items.price')
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
  
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }

  def calculate_total_price
    self.total_price = quantity * item.price
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :carts, through: :cart_items

  has_one_attached :image
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    has_many :transaction_items, dependent: :destroy
end

app/models/transaction_item.rb
class TransactionItem < ApplicationRecord
    belongs_to :transaction_record, class_name: 'Transaction'
end
  
  

app/models/user.rb
class User < ApplicationRecord
  has_one :cart
  has_many :cart_items, through: :cart
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    user_type == 'admin'
  end
end

app/controllers/admin/transactions_controller.rb
class Admin::TransactionsController < ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin!

    def index
        @transactions = Transaction.order(created_at: :desc)
        @transaction_items = TransactionItem.all
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart = current_user.cart || current_user.create_cart

  end

  def add_item
    @cart = current_user.cart || current_user.create_cart
    item = Item.find(params[:item_id])

    # Check if the item already exists in the cart, increase the quantity if so
    @cart_item = @cart.cart_items.find_by(item_id: item.id)
    if @cart_item
      @cart_item.update(quantity: @cart_item.quantity + 1)
      @cart_item.update(total_price: @cart_item.item.price * @cart_item.quantity)
    else
      @cart.cart_items.create(item: item, quantity: 1)
    end
    flash[:alert] = "#{item.item_name} has been added to your cart."
    redirect_to root_path
  end

  def remove_item
    cart_item = CartItem.find(params[:cart_item_id])
    cart_item.destroy

    redirect_to cart_path
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :check_admin, only: [:edit, :update]

  def admin_only
    redirect_to root_path, alert: 'Access denied' unless current_user&.admin?
  end

  # GET /items or /items.json
  def index
    flash[:notice] = ' '
    @items = Item.all
  end

  def search
    @items = Item.where('item_name LIKE ?', "%#{params[:query]}%")
  end

  # GET /items/1 or /items/1.json
  def show
    @item = Item.find(params[:id])
  end

  


  def description
    @item = Item.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:item_name, :item_description, :price)
    end

    def check_admin
      unless current_user.admin?
        redirect_to items_path, alert: "You are not authorized to edit items."
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.order(created_at: :desc)
    @transaction_items = TransactionItem.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy!

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.fetch(:transaction, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path, notice: 'Profile updated successfully'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :contact_number, :address)
  end
end

app/helpers/admin/transactions_helper.rb
module Admin::TransactionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/index_home_helper.rb
module IndexHomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/transactions/index.html.erb
<div class="admin-container">
  <div class="admin-sidebar bg-gray-800">
        <p>
            <%= link_to admin_dashboard_path do %>
                <i class="fa-solid fa-table-columns"></i> Dashboard
            <% end %>
        </p>

        <p class="current-page"><%= link_to admin_transactions_path do %>
            <i class="fa-solid fa-box"></i> Transactions
        <% end %></p>

        <p><%= link_to admin_items_path do %>
            <i class="fa-solid fa-list"></i> Item List
        <% end %></p>

        <p><%= link_to admin_user_list_index_path do %>
            <i class="fa-solid fa-users"></i> Users
        <% end %></p>

        <p><%= render 'shared/logout_button' %></p>
  </div>
  <div class="admin-sidebar-content">
    <div class="content-header">
      <h1 class="content-title">Transactions
        <span class="item-buttons"></span></h1>
    </div>
    <h1 class="text-lg text-white font-medium">All Transactions</h1>
    <div class="flex flex-col mt-6 w-3/5">
        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8 max-h-96">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden sm:rounded-lg">
                    <table class="min-w-full text-md text-gray-200">
                        <thead class="bg-gray-800 text-md uppercase font-medium">
                            <tr class="">
                                <th scope="col" class="px-6 py-3 text-center tracking-wider">
                                    User
                                </th>
                                <th scope="col" class="px-6 py-3 text-center tracking-wider">
                                    Quantity | Item
                                </th>
                                <th scope="col" class="px-6 py-3 ext-center tracking-wider">
                                    Total Amount
                                </th>
                                <th scope="col" class="px-6 py-3 ext-center tracking-wider">
                                    Date
                                </th>
                            </tr>
                        </thead>
                        <tbody class="bg-gray-800 text-center">
                            <% @transactions.each do |txn| %>
                                <tr class="bg-black bg-opacity-20">
                                    <td class="flex px-6 py-4 whitespace-nowrap text-center">
                                        <span class="ml-2 font-medium text-center"><%= txn.user_email %></span>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        <% @transaction_items.each do |item| %>
                                            <% if item.transaction_id == txn.id %>
                                                <%= item.item_quantity%> | <%= item.item_name %><br>
                                            <% end %>
                                        <% end %>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        <%= number_to_currency(txn.total_amount) %>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        <%= txn.created_at.strftime("%b %d, %Y %H:%M") %>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
  </div>
</div>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
</div>

app/views/transactions/index.html.erb
<div id="transactions" class="w-3/5 mx-auto font-bold	">
  
      <h2 class="mt-6 text-2xl text-violet-900">Transactions</h2>
      <%= link_to 'Back to Profile', user_path, class: "underline text-violet-900 text-sm hover:text-white" %>
      <div class="overflow-x-auto max-h-96">
        <table class="w-full text-sm text-left text-gray-500">
            <thead class="text-xs text-white uppercase bg-violet-900">
                <tr>
                    <th scope="col" class="px-6 py-3">
                        User
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Quantity | Items
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Total Amount
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Date
                    </th>
                </tr>
            </thead>
            <tbody>
              <% @transactions.each do |txn| %>
                <% if txn.user_email == current_user.email %>
                  <tr class="bg-white border-b">
                      <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                        <%= txn.user_email %>
                      </th>
                      <td class="px-6 py-4">
                        <% @transaction_items.each do |item| %>
                          <% if item.transaction_id == txn.id %>
                            <%= item.item_quantity%> | <%= item.item_name %><br>
                          <% end %>
                        <% end %>
                      </td>
                      <td class="px-6 py-4">
                        <%= number_to_currency(txn.total_amount, unit: "₱", format: "%u%n" ) %>
                      </td>
                      <td class="px-6 py-4">
                        <%= txn.created_at.strftime("%b %d, %Y %H:%M") %>
                      </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
        </table>
      </div>
    
</div>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transaction %>

<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  <%= link_to "Back to transactions", transactions_path %>

  <%= button_to "Destroy this transaction", @transaction, method: :delete %>
</div>